import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import CustomLink from "./componants/CustomLink";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <ul className="flex gap-x-[20px] font-bold text-[22px] p-[30px] cursor-pointer">
            <li><CustomLink path='/'>Home</CustomLink></li>
            <li><CustomLink path='/about'>About</CustomLink></li>
            <li><CustomLink path='/blog'>Blog</CustomLink></li>
            <li><CustomLink path='/dashbord/setting'>Setting</CustomLink></li>
            <li><CustomLink path='/dashbord/analytics'>Analytics</CustomLink></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
